
services:
  app:
    build: .
    restart: unless-stopped
    volumes:
      - ./:/app
    ports:
      - 7777:7777
    depends_on:
      - "database"
      - flyway
    env_file:
      - .env
      
  database:
    container_name: "postgres-database"
    image: "postgres:13.4"
    restart: unless-stopped
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
    env_file:
      - .env
  flyway:
    image: flyway/flyway:7.3.0-alpine
    environment:
      - FLYWAY_USER=username
      - FLYWAY_PASSWORD=password
      - FLYWAY_URL=jdbc:postgresql://postgres-database:5432/database
    depends_on:
      - database
    volumes:
      - .:/flyway/sql
    command: -connectRetries=60 -baselineOnMigrate=true migrate